// Mobile sign-in & "pair with desktop" QR flow.
// Two screens side-by-side in one artboard:
//   1. Sign in (phone) — short, with passkey-first CTA
//   2. Pair with desktop — show the QR code scanner state for fast pairing

const { KevinWordmark, Icon, I, Badge } = window;

// Small fake QR — generated by stippling cells. Not a real QR.
const FauxQR = ({ size = 168, cellSize = 8 }) => {
  const cells = size / cellSize;
  // deterministic pattern based on cell index
  const filled = (x, y) => {
    if ((x < 3 && y < 3) || (x >= cells - 3 && y < 3) || (x < 3 && y >= cells - 3)) {
      // corner finders
      if (x === 0 || x === 2 || y === 0 || y === 2 || (x === 1 && y === 1) || (x >= cells - 3 && (x === cells - 1 || x === cells - 3)) || (y >= cells - 3 && (y === cells - 1 || y === cells - 3))) return true;
      return false;
    }
    return ((x * 31 + y * 17 + x * y) % 7) < 3;
  };
  const dots = [];
  for (let y = 0; y < cells; y++) {
    for (let x = 0; x < cells; x++) {
      if (filled(x, y)) dots.push(<rect key={`${x},${y}`} x={x * cellSize} y={y * cellSize} width={cellSize} height={cellSize} fill="#0a0a0c" rx={1.4} />);
    }
  }
  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} style={{ display: 'block', borderRadius: 10 }}>
      <rect width={size} height={size} fill="#fff" />
      {dots}
      {/* center logo cutout */}
      <rect x={size/2 - 18} y={size/2 - 18} width={36} height={36} fill="#fff" />
      <text x={size/2} y={size/2 + 5} textAnchor="middle" style={{ fontFamily: 'var(--k-font-ui)', fontWeight: 700, fontSize: 14, fill: '#0a0a0c' }}>K</text>
    </svg>
  );
};

// ─── Phone-shaped artboard helper ────────────────────────────
const MobileShell = ({ children, label }) => (
  <div className="k-mob k-mob--light">
    <div className="k-mob-status k-mob-status--light">
      <span className="k-mob-time">9:41</span>
      <div className="k-mob-status-r">
        <span><Icon d={I.wifi} size={11} /></span>
        <span className="k-mob-battery k-mob-battery--light"><span /></span>
      </div>
    </div>
    <div style={{ flex: 1, display: 'flex', flexDirection: 'column', minHeight: 0 }}>
      {children}
    </div>
    <div className="k-mob-home k-mob-home--light" />
  </div>
);

// ─── Screen 1 · Sign in (phone) ─────────────────────────────
const MobileSignIn = () => (
  <MobileShell>
    <div style={{ padding: '36px 24px 24px', flex: 1, display: 'flex', flexDirection: 'column' }}>
      <KevinWordmark href={null} size={18} suffix={true} />
      <div style={{ marginTop: 56 }}>
        <div style={{ fontSize: 11, color: 'var(--k-fg-4)', fontFamily: 'var(--k-font-mono)', textTransform: 'uppercase', letterSpacing: '0.06em', fontWeight: 600 }}>Sign in</div>
        <h1 style={{ fontFamily: 'var(--k-font-display)', fontWeight: 400, fontSize: 34, letterSpacing: '-0.025em', margin: '6px 0 8px', lineHeight: 1.08 }}>Welcome back.</h1>
        <p style={{ fontSize: 13, color: 'var(--k-fg-3)', margin: 0, lineHeight: 1.5 }}>Sign in on this phone to capture photos for an existing claim, or pair with the desktop session you have open.</p>
      </div>

      <div style={{ marginTop: 28, display: 'flex', flexDirection: 'column', gap: 12 }}>
        <div className="k-insp-field">
          <label>Work email</label>
          <input className="k-insp-input" placeholder="you@example.com" style={{ fontSize: 15, padding: '12px 14px' }} />
        </div>
        <div className="k-insp-field">
          <label style={{ display: 'flex', justifyContent: 'space-between' }}>
            <span>Password</span>
            <button type="button" className="k-link" style={{ fontSize: 11.5 }}>Forgot?</button>
          </label>
          <input className="k-insp-input" type="password" placeholder="Your password" style={{ fontSize: 15, padding: '12px 14px' }} />
        </div>
        <button className="k-btn k-btn--lg" style={{ width: '100%', justifyContent: 'center', padding: '14px 18px', fontSize: 14 }}>
          Sign in
        </button>
      </div>

      <div className="k-auth-or" style={{ margin: '24px 0' }}><span>or</span></div>

      <button className="k-btn k-btn--ghost k-btn--lg" style={{ width: '100%', justifyContent: 'center', padding: '14px 18px', fontSize: 14 }}>
        <Icon d={<><rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/></>} size={14} />
        Pair with desktop instead
      </button>

      <div style={{ marginTop: 'auto', paddingTop: 24, fontSize: 11.5, color: 'var(--k-fg-4)', textAlign: 'center' }}>
        First time? <button className="k-link" style={{ fontSize: 11.5 }}>Open kevin.co on a laptop →</button>
      </div>
    </div>
  </MobileShell>
);

// ─── Screen 2 · Pair with desktop ───────────────────────────
const MobilePair = () => (
  <MobileShell>
    <div style={{ padding: '20px 20px 0', display: 'flex', alignItems: 'center', gap: 10 }}>
      <a className="k-mob-back k-mob-back--light" href="26-Mobile-sign-in.html" title="Back to mobile sign-in">
        <Icon d={I.chevleft} size={14} />
      </a>
      <span style={{ fontSize: 13, fontWeight: 600 }}>Pair with desktop</span>
    </div>

    <div style={{ padding: '14px 24px 0', flex: 1, display: 'flex', flexDirection: 'column' }}>
      <p style={{ fontSize: 13, color: 'var(--k-fg-3)', margin: 0, lineHeight: 1.5 }}>
        Open your desktop claim, click <strong>Add photos from phone</strong>, and point your camera at the code shown there.
      </p>

      {/* Camera viewfinder framing */}
      <div className="k-pair-view">
        <div className="k-pair-corner k-pair-corner--tl" />
        <div className="k-pair-corner k-pair-corner--tr" />
        <div className="k-pair-corner k-pair-corner--bl" />
        <div className="k-pair-corner k-pair-corner--br" />
        {/* live "found a QR" indicator */}
        <div className="k-pair-found">
          <FauxQR size={172} cellSize={8} />
          <div className="k-pair-found-ring" />
        </div>
      </div>

      <div className="k-pair-status">
        <div className="k-pulse k-pulse--sm" />
        <div style={{ fontSize: 12.5 }}>
          <strong style={{ color: 'var(--k-fg)' }}>Code detected — confirming…</strong>
          <div style={{ fontSize: 11, color: 'var(--k-fg-4)', marginTop: 2, fontFamily: 'var(--k-font-mono)' }}>kvn-pair-7HX42-MQ9R</div>
        </div>
      </div>

      <div className="k-pair-claim">
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div>
            <div style={{ fontSize: 11, color: 'var(--k-fg-4)', fontFamily: 'var(--k-font-mono)', textTransform: 'uppercase', letterSpacing: '0.05em', fontWeight: 600 }}>Pairing with</div>
            <div style={{ fontSize: 13.5, fontWeight: 600, marginTop: 3 }}>Godfrey — Kitchen fire</div>
            <div style={{ fontSize: 11.5, color: 'var(--k-fg-3)', marginTop: 2 }}>CLM-2026-04412 · Mac · Safari · Smithtown</div>
          </div>
          <span style={{ width: 38, height: 38, borderRadius: 99, background: 'var(--k-fg-2)', color: 'var(--k-bg)', display: 'grid', placeItems: 'center', fontWeight: 600, fontSize: 13 }}>MR</span>
        </div>
        <a className="k-btn k-btn--lg" href="11-Mobile-capture.html" style={{ width: '100%', justifyContent: 'center', marginTop: 14, padding: '12px', fontSize: 14 }}>
          Pair to this claim
        </a>
        <a className="k-link" href="26-Mobile-sign-in.html" style={{ display: 'block', textAlign: 'center', width: '100%', marginTop: 10, fontSize: 11.5 }}>
          Cancel
        </a>
      </div>

      <div style={{ marginTop: 'auto', paddingTop: 16, paddingBottom: 12, fontSize: 11, color: 'var(--k-fg-4)', textAlign: 'center', lineHeight: 1.45 }}>
        Pairing only sends photos and capture notes. Your desktop session stays in control of edits and exports.
      </div>
    </div>
  </MobileShell>
);

Object.assign(window, { MobileSignIn, MobilePair, FauxQR });
