import { useMemo, useState } from 'react'
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom'
import { I, Icon } from '../components/Icon'
import KevinWordmark from '../components/KevinWordmark'
import { MktFooter } from '../components/MarketingChrome'
import {
  DOC_ARTICLES,
  DOC_NAV,
  type DocBlockTuple,
} from '../content/docs-content.generated'

/**
 * Docs — ported from design/components/docs.jsx.
 *
 * The CONTENT is not ported. `src/content/docs-content.generated.ts` is
 * generated by design/build-docs-exports.cjs from the same block tuples that
 * feed Kevin-docs.md and gitbook/. Hand-copying 45 articles into src/ would
 * have made a fourth copy to drift, which is the exact failure that script was
 * written to end. Edit design/components/docs-articles{,-2,-3}.jsx, then run
 * `node build-docs-exports.cjs` from design/ — all three targets update.
 *
 * ONE deviation: every article has its own URL (/docs/<slug>) instead of living
 * in component state at a single /docs. In a standalone prototype page that
 * choice costs nothing; on the live site it would publish 45 articles as one
 * indexable page, break every deep link into the docs, and make the browser
 * back button skip the whole section. Nav items, search results and the pager
 * are links now, so all three work. /docs redirects to the first article.
 */

const DOC_FLAT = DOC_NAV.flatMap((s) =>
  s.items.map(([id, label]) => ({ id, label, section: s.section })),
)
const DOC_SECTION_OF = (slug: string) =>
  DOC_NAV.find((s) => s.items.some(([id]) => id === slug))?.section ?? ''

// Matches the in-page anchors the generated exports use.
const docSlugify = (s: string) =>
  'h-' + String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

function DocBlock({ block }: { block: DocBlockTuple }) {
  const [kind, payload] = block
  if (kind === 'h2')
    return (
      <h2 className="k-docs-h2" id={docSlugify(payload)}>
        {payload}
      </h2>
    )
  if (kind === 'p') return <p>{payload}</p>
  if (kind === 'ul')
    return (
      <ul className="k-docs-list">
        {payload.map((it) => (
          <li key={it}>{it}</li>
        ))}
      </ul>
    )
  if (kind === 'ol')
    return (
      <ol className="k-docs-list k-docs-list--num">
        {payload.map((it) => (
          <li key={it}>{it}</li>
        ))}
      </ol>
    )
  if (kind === 'code') return <pre className="k-docs-code">{payload}</pre>
  if (kind === 'note')
    return (
      <div className="k-docs-callout">
        <Icon d={I.info} size={14} />
        <div>{payload}</div>
      </div>
    )
  if (kind === 'table') {
    const [head, ...rows] = payload
    return (
      <div className="k-docs-tablewrap">
        <table className="k-docs-table">
          <thead>
            <tr>
              {head.map((h) => (
                <th key={h}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((r) => (
              <tr key={r.join('|')}>
                {r.map((c, j) => (
                  <td key={j}>{c}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    )
  }
  return null
}

/** The design's scroll walk: find whatever actually scrolls and nudge it. */
function scrollToHeading(heading: string) {
  const el = document.getElementById(docSlugify(heading))
  if (!el) return
  let node: HTMLElement | null = el.parentElement
  while (node && node !== document.body) {
    const oy = getComputedStyle(node).overflowY
    if ((oy === 'auto' || oy === 'scroll') && node.scrollHeight > node.clientHeight + 4) break
    node = node.parentElement
  }
  const target = el.getBoundingClientRect().top
  if (node && node !== document.body) {
    node.scrollTop += target - node.getBoundingClientRect().top - 16
  } else {
    const se = (document.scrollingElement || document.documentElement) as HTMLElement
    se.scrollTop += target - 76
  }
}

export default function DocsPage() {
  const { slug } = useParams()
  const navigate = useNavigate()
  const [q, setQ] = useState('')

  const hits = useMemo(() => {
    if (!q.trim()) return null
    const needle = q.toLowerCase()
    return DOC_FLAT.filter((a) => {
      const d = DOC_ARTICLES[a.id]
      if (!d) return false
      const body = d.blocks.map((b) => (Array.isArray(b[1]) ? JSON.stringify(b[1]) : b[1])).join(' ')
      return (a.label + ' ' + d.summary + ' ' + body).toLowerCase().includes(needle)
    })
  }, [q])

  if (!slug) return <Navigate to={`/docs/${DOC_FLAT[0].id}`} replace />
  const art = DOC_ARTICLES[slug]
  if (!art) return <Navigate to={`/docs/${DOC_FLAT[0].id}`} replace />

  const idx = DOC_FLAT.findIndex((a) => a.id === slug)
  const prev = idx > 0 ? DOC_FLAT[idx - 1] : null
  const next = idx < DOC_FLAT.length - 1 ? DOC_FLAT[idx + 1] : null
  const headings = art.blocks.filter((b) => b[0] === 'h2').map((b) => b[1] as string)

  const open = (id: string) => {
    setQ('')
    navigate(`/docs/${id}`)
    const se = (document.scrollingElement || document.documentElement) as HTMLElement
    se.scrollTop = 0
  }

  return (
    <div className="k-docs">
      <header className="k-topbar">
        <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
          <KevinWordmark size={16} suffix to="/" />
          <div style={{ width: 1, height: 16, background: 'var(--k-line)' }} />
          <span style={{ fontSize: 13, color: 'var(--k-fg-2)' }}>Docs</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div className="k-search" style={{ minWidth: 320 }}>
            <Icon d={I.search} size={12} />
            <input
              placeholder={`Search ${DOC_FLAT.length} articles`}
              value={q}
              onChange={(e) => setQ(e.target.value)}
            />
            {q && (
              <button type="button" className="k-icon-btn" onClick={() => setQ('')} title="Clear">
                ✕
              </button>
            )}
          </div>
          <Link className="k-btn k-btn--ghost" to="/sign-in">
            Sign in
          </Link>
          <Link className="k-btn" to="/sign-in">
            Start a claim
          </Link>
        </div>
      </header>

      <div className="k-docs-body">
        <aside className="k-docs-nav">
          {DOC_NAV.map((sec) => (
            <div key={sec.section} style={{ marginBottom: 18 }}>
              <div className="k-docs-nav-h">{sec.section}</div>
              {sec.items.map(([id, label]) => (
                <button
                  type="button"
                  key={id}
                  className={`k-docs-nav-item ${id === slug ? 'k-docs-nav-item--on' : ''}`}
                  onClick={() => open(id)}
                >
                  {label}
                </button>
              ))}
            </div>
          ))}
        </aside>

        <main className="k-docs-main">
          {hits ? (
            <>
              <h1 className="k-docs-h1">
                {hits.length} result{hits.length === 1 ? '' : 's'}
              </h1>
              <p className="k-docs-lede">
                Matching “{q}” across all {DOC_FLAT.length} articles.
              </p>
              <div className="k-docs-results">
                {hits.map((h) => (
                  <button
                    type="button"
                    key={h.id}
                    className="k-docs-result"
                    onClick={() => open(h.id)}
                  >
                    <span className="k-docs-result-sec">{h.section}</span>
                    <span className="k-docs-result-t">{h.label}</span>
                    <span className="k-docs-result-d">{DOC_ARTICLES[h.id].summary}</span>
                  </button>
                ))}
                {hits.length === 0 && (
                  <p style={{ color: 'var(--k-fg-3)' }}>
                    Nothing matched. Try a shorter phrase, or email kevin@kevin.co.
                  </p>
                )}
              </div>
            </>
          ) : (
            <>
              <div className="k-docs-bread">
                <span>{DOC_SECTION_OF(slug)}</span>
                <Icon d={I.chevright} size={10} />
                <span style={{ color: 'var(--k-fg)' }}>{art.title}</span>
              </div>
              <h1 className="k-docs-h1">{art.title}</h1>
              <p className="k-docs-lede">{art.summary}</p>

              {headings.length > 2 && (
                <div className="k-docs-toc">
                  <div
                    style={{
                      fontSize: 11,
                      color: 'var(--k-fg-4)',
                      textTransform: 'uppercase',
                      letterSpacing: '0.06em',
                      fontWeight: 600,
                      marginBottom: 8,
                    }}
                  >
                    In this article
                  </div>
                  {headings.map((h, i) => (
                    <button
                      type="button"
                      key={h}
                      className="k-docs-toc-item"
                      onClick={() => scrollToHeading(h)}
                    >
                      <span
                        style={{
                          fontFamily: 'var(--k-font-mono)',
                          color: 'var(--k-fg-4)',
                          fontSize: 11,
                          width: 26,
                        }}
                      >
                        {String(i + 1).padStart(2, '0')}
                      </span>
                      <span>{h}</span>
                    </button>
                  ))}
                </div>
              )}

              <div className="k-docs-article">
                {art.blocks.map((b, i) => (
                  <DocBlock key={i} block={b} />
                ))}
              </div>

              <div className="k-docs-pager">
                {prev ? (
                  <button type="button" className="k-docs-pagebtn" onClick={() => open(prev.id)}>
                    <span className="k-docs-pagebtn-l">← Previous</span>
                    <span className="k-docs-pagebtn-t">{prev.label}</span>
                  </button>
                ) : (
                  <div />
                )}
                {next ? (
                  <button
                    type="button"
                    className="k-docs-pagebtn k-docs-pagebtn--next"
                    onClick={() => open(next.id)}
                  >
                    <span className="k-docs-pagebtn-l">Next →</span>
                    <span className="k-docs-pagebtn-t">{next.label}</span>
                  </button>
                ) : (
                  <div />
                )}
              </div>

              <div className="k-docs-help">
                Still stuck? Email{' '}
                <a
                  href="mailto:kevin@kevin.co"
                  style={{ color: 'var(--k-accent)', fontWeight: 600, textDecoration: 'underline' }}
                >
                  kevin@kevin.co
                </a>{' '}
                — it goes straight to a person who has settled claims.
              </div>
            </>
          )}
        </main>
      </div>
      {/* Public page (/docs): without this the page dead-ends with no route to
          Privacy, Terms or About, and carries none of the legal-identity trust
          signals SEO.md wants on indexed pages. */}
      <MktFooter />
    </div>
  )
}
