// GENERATED by scripts/build-depreciation-reference.mjs -- do not edit.
// Source of truth: GET /v1/depreciation-rules on the live backend.
// Refresh with: node scripts/build-depreciation-reference.mjs
// Verify with:  node scripts/build-depreciation-reference.mjs --check
// Captured: 2026-10-05

export type ScheduleRefRow = {
  category: string
  item: string
  years: number | null
  how: string
  flatPct: number | null
  maxPct: number | null
  appraisal: boolean
  note: string | null
}

export const SCHEDULE_COUNTS = {
  "lines": 87,
  "categories": 31,
  "appraisal": 6,
  "noUsefulLife": 14,
  "capped": 1
} as const

export const SCHEDULE_CAPTURED = '2026-10-05'

export const SCHEDULE_ROWS: ScheduleRefRow[] = [
  {
    "category": "Appliances — Major",
    "item": "All Other Major Appliances",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Appliances — Major",
    "item": "Refrigerator",
    "years": 14,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Appliances — Small",
    "item": "All Other Small Appliances",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Artwork",
    "item": "All Other Artwork Items",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Artwork",
    "item": "Paintings & Tapestry",
    "years": null,
    "how": "Percentage of replacement cost",
    "flatPct": null,
    "maxPct": null,
    "appraisal": true,
    "note": "Schedule: use Replacement Cost -- holds value, does not depreciate."
  },
  {
    "category": "Automotive & Motorcycle Accessories",
    "item": "All Other Auto & Motorcycle Accessories",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Automotive & Motorcycle Accessories",
    "item": "Automotive Working Parts",
    "years": 5,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Automotive & Motorcycle Accessories",
    "item": "Trailers",
    "years": 20,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Books, Magazines & Periodicals",
    "item": "Paperback & Hardcover Books",
    "years": null,
    "how": "Flat rate",
    "flatPct": 0.5,
    "maxPct": null,
    "appraisal": false,
    "note": "Schedule: flat 50%, age-independent."
  },
  {
    "category": "Books, Magazines & Periodicals",
    "item": "Text Book",
    "years": 5,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Business Equipment & Goods",
    "item": "Business Equipment & Goods",
    "years": null,
    "how": "Does not depreciate",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": "Schedule: N/A, 0% annual, 0% max -- does not depreciate under this schedule at all (it is not personal property)."
  },
  {
    "category": "Cameras, Camcorders & Equipment",
    "item": "All Cameras & Camcorders",
    "years": 20,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Cameras, Camcorders & Equipment",
    "item": "Flashes & Accessories",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Clothing & Accessories",
    "item": "All Other Clothing",
    "years": 8,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Clothing & Accessories",
    "item": "Footwear — Non-Athletic",
    "years": 5,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": "DIVERGENCE from the published schedule (owner, repeatedly, 2026-09-09/10). The schedule files ALL footwear under 'Socks & Footwear' at 3 years. Three years is the ATHLETIC life -- it belongs to shoes that are run in -- and applying it to a Converse, a sandal or a $300 leather dress shoe is not defensible. Non-athletic footwear sits at 5. Only genuinely athletic footwear gets the 3-year Sporting Goods line."
  },
  {
    "category": "Clothing & Accessories",
    "item": "Furs",
    "years": null,
    "how": "Valued manually",
    "flatPct": null,
    "maxPct": null,
    "appraisal": true,
    "note": "DIVERGENCE from the published schedule, which has no Furs line and would file a mink under All Other Clothing at 8 years. Furs are appraisal-grade and carry policy sub-limits; we have never auto-priced them and Phase 4 must not start. Kept as an appraisal line so the gate follows the schedule id."
  },
  {
    "category": "Clothing & Accessories",
    "item": "Socks & Hosiery",
    "years": 3,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Clothing & Accessories",
    "item": "Underwear & Nightwear",
    "years": 3,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Computer & Related Goods",
    "item": "All Computer & Related Goods",
    "years": 4.5,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Computer & Related Goods",
    "item": "Printers, Peripherals & Accessories",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Electronics",
    "item": "All Other Electronics",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Electronics",
    "item": "Cellular Phone",
    "years": 5,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Firearms",
    "item": "All Firearms",
    "years": 20,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": true,
    "note": null
  },
  {
    "category": "Furniture — Home & Office",
    "item": "All Other Furniture Items",
    "years": 20,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Furniture — Home & Office",
    "item": "Children's Furniture",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Furniture — Home & Office",
    "item": "Upholstered Furniture",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Health & Personal Care",
    "item": "All Other Health Care",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Health & Personal Care",
    "item": "Medicine",
    "years": 3,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Hobbies & Collectibles",
    "item": "All Other Hobbies & Collectibles",
    "years": 20,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": "Schedule: 20 years, straight-line."
  },
  {
    "category": "Hobbies & Collectibles",
    "item": "Art Supplies",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Hobbies & Collectibles",
    "item": "Collectible Coins / Numismatic Items",
    "years": null,
    "how": "Percentage of replacement cost",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": "Schedule: use Replacement Cost (indefinite life)."
  },
  {
    "category": "Hobbies & Collectibles",
    "item": "Perishables (Marijuana)",
    "years": 0.1667,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": "Schedule: 2 MONTHS, 600%/yr, 100% max. The shortest life in the whole schedule, and the only one measured in months -- which is why useful_life is a float."
  },
  {
    "category": "Hobbies & Collectibles",
    "item": "Sewing Machines",
    "years": 20,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Hobbies & Collectibles",
    "item": "Smoking & Vaping Accessories",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Hobbies & Collectibles",
    "item": "Trading Cards & Comic Books",
    "years": null,
    "how": "Percentage of replacement cost",
    "flatPct": null,
    "maxPct": null,
    "appraisal": true,
    "note": "Schedule: use Replacement Cost."
  },
  {
    "category": "Housewares — Dining & Flat Ware",
    "item": "All Other Silver & Dining Ware",
    "years": 20,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Housewares — Dining & Flat Ware",
    "item": "Fine China",
    "years": null,
    "how": "Percentage of replacement cost",
    "flatPct": null,
    "maxPct": null,
    "appraisal": true,
    "note": "Schedule: use Replacement Cost."
  },
  {
    "category": "Housewares — Home Décor",
    "item": "All Other Houseware Items",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Housewares — Home Décor",
    "item": "Clocks, Mirrors & Fireplaces",
    "years": 20,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Housewares — Home Décor",
    "item": "Figurines",
    "years": null,
    "how": "Flat rate",
    "flatPct": 0.1,
    "maxPct": null,
    "appraisal": false,
    "note": "Schedule: flat 10%, age-independent."
  },
  {
    "category": "Infant & Baby Related Goods",
    "item": "All Infant & Baby Related Goods",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Jewelry & Watches",
    "item": "All Other Jewelry",
    "years": null,
    "how": "Percentage of replacement cost",
    "flatPct": null,
    "maxPct": null,
    "appraisal": true,
    "note": "Schedule: use Replacement Cost."
  },
  {
    "category": "Jewelry & Watches",
    "item": "Costume Jewelry & Children's Watches",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Jewelry & Watches",
    "item": "Watches, Broaches, Pins & Cuff Links",
    "years": 20,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Kitchenware",
    "item": "All Other Kitchenware",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Kitchenware",
    "item": "Cutlery & Stainless Steel Kitchenware",
    "years": 20,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Kitchenware",
    "item": "Miscellaneous Utensils",
    "years": 5,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Lawn, Garden & Patio",
    "item": "All Other Lawn, Garden & Patio",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Lawn, Garden & Patio",
    "item": "Fabric Cushions & Umbrellas",
    "years": 3,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Lawn, Garden & Patio",
    "item": "Gardening Clothing",
    "years": 8,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Lawn, Garden & Patio",
    "item": "Lawn Furniture",
    "years": 7,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Lawn, Garden & Patio",
    "item": "Power Mowers & Electric Yard Tools",
    "years": 7,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Linens & Softgoods",
    "item": "All Other Linens & Softgoods",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Linens & Softgoods",
    "item": "Kitchen Linens",
    "years": 5,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Linens & Softgoods",
    "item": "Quilts",
    "years": 20,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Linens & Softgoods",
    "item": "Sheets, Pillow Cases & Towels",
    "years": 5,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Luggage, Bags & Accessories",
    "item": "All Other Luggage & Bags",
    "years": 20,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Luggage, Bags & Accessories",
    "item": "Handbags & Money Carriers",
    "years": 4,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Music, Movies & Media",
    "item": "Cassette Tapes",
    "years": null,
    "how": "Flat rate",
    "flatPct": 0.5,
    "maxPct": null,
    "appraisal": false,
    "note": "Schedule: flat 50%."
  },
  {
    "category": "Music, Movies & Media",
    "item": "CDs",
    "years": null,
    "how": "Flat rate",
    "flatPct": 0.25,
    "maxPct": null,
    "appraisal": false,
    "note": "Schedule: flat 25%."
  },
  {
    "category": "Music, Movies & Media",
    "item": "DVDs",
    "years": 8,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": 0.5,
    "appraisal": false,
    "note": "Schedule: 8 years, 12.5%/yr, 50% MAX -- the one line in the whole schedule that caps below 100%."
  },
  {
    "category": "Musical Instruments",
    "item": "All Other Instruments",
    "years": 20,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Musical Instruments",
    "item": "Instrument Accessories",
    "years": 5,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Musical Instruments",
    "item": "Instrument Parts & DJ Equipment",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Office Supplies",
    "item": "All Other Office Supplies",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Office Supplies",
    "item": "Safes & Vaults",
    "years": 50,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Perishable — Non-perishable",
    "item": "Opened Cleaning Supplies",
    "years": null,
    "how": "Flat rate",
    "flatPct": 0.5,
    "maxPct": null,
    "appraisal": false,
    "note": "Schedule: flat 50%."
  },
  {
    "category": "Perishable — Non-perishable",
    "item": "Unopened Cleaning Supplies",
    "years": null,
    "how": "Does not depreciate",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": "Schedule: N/A, 0% annual, 0% max -- sealed stock is replaced at full cost."
  },
  {
    "category": "Personal Care & Beauty",
    "item": "All Other Personal Care",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Personal Care & Beauty",
    "item": "Cosmetics",
    "years": null,
    "how": "Flat rate",
    "flatPct": 0.5,
    "maxPct": null,
    "appraisal": false,
    "note": "Schedule: flat 50%."
  },
  {
    "category": "Personal Care & Beauty",
    "item": "Hair Brushes & Dental Care",
    "years": 5,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Pet & Animal Supplies",
    "item": "All Pet & Animal Supplies",
    "years": 5,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Sporting Goods",
    "item": "All Other Sporting Goods",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Sporting Goods",
    "item": "Archery & Hunting",
    "years": 15,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Sporting Goods",
    "item": "Athletic Shoes & Cleats",
    "years": 3,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": "Schedule: 3 years, 33.33%/yr, 100% max. The line that started this whole exercise (carrier dispute, 2026-09-09)."
  },
  {
    "category": "Sporting Goods",
    "item": "Billiard Table",
    "years": 14,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Sporting Goods",
    "item": "Knives & Optics",
    "years": 20,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Sporting Goods",
    "item": "Racquetball & Table Tennis Acces.",
    "years": 3,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Sporting Goods",
    "item": "Roller/In-line Skates",
    "years": 7,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Sporting Goods",
    "item": "Soccer & Tennis",
    "years": 5,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Sporting Goods",
    "item": "Table Tennis Table & Ice Skates",
    "years": 6,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Sporting Goods",
    "item": "Tennis Apparel",
    "years": 8,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Tools",
    "item": "All Tools & Accessories",
    "years": 20,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Toys & Games",
    "item": "All Other Toys",
    "years": 2,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Toys & Games",
    "item": "Children's Furniture",
    "years": 10,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Toys & Games",
    "item": "Games, Video Games & Electronic Toys",
    "years": 5,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  },
  {
    "category": "Toys & Games",
    "item": "Outdoor Toys",
    "years": 5,
    "how": "Straight line by age",
    "flatPct": null,
    "maxPct": null,
    "appraisal": false,
    "note": null
  }
]
