// GENERATED by design/build-docs-exports.cjs -- do not edit.
// Source of truth: design/components/docs-articles{,-2,-3}.jsx and the
// DOC_NAV literal in design/components/docs.jsx. Edit those, then run
//   node build-docs-exports.cjs
// from design/. Editing this file is discarded on the next run.

export type DocBlockTuple =
  | ['h2', string]
  | ['p', string]
  | ['ul', string[]]
  | ['ol', string[]]
  | ['code', string]
  | ['note', string]
  | ['table', string[][]]

export type DocArticle = { title: string; summary: string; blocks: DocBlockTuple[] }
export type DocNavSection = { section: string; items: [string, string][] }

export const DOC_COUNTS = { articles: 45, sections: 8 }

export const DOC_NAV: DocNavSection[] = [
  {
    "section": "Getting started",
    "items": [
      [
        "quick-start",
        "Quick start"
      ],
      [
        "first-claim",
        "Creating your first claim"
      ],
      [
        "uploading-photos",
        "Uploading photos"
      ],
      [
        "photo-sets",
        "Reviewing photo sets"
      ],
      [
        "reviewing-worksheet",
        "Reviewing the worksheet"
      ],
      [
        "exporting-xactimate",
        "Exporting to Xactimate"
      ]
    ]
  },
  {
    "section": "Worksheet",
    "items": [
      [
        "editing-cells",
        "Editing cells"
      ],
      [
        "bulk-actions",
        "Bulk actions"
      ],
      [
        "search-filter",
        "Search & filter"
      ],
      [
        "content-classes",
        "Content classes"
      ],
      [
        "depreciation-overrides",
        "Depreciation overrides"
      ],
      [
        "rcv-comps",
        "RCV comps & proof links"
      ],
      [
        "unpriced-items",
        "Unpriced items"
      ],
      [
        "special-limits",
        "Special-limits flags"
      ],
      [
        "item-panel",
        "The item panel"
      ]
    ]
  },
  {
    "section": "Exporting",
    "items": [
      [
        "format-xlsx",
        "Xactimate (Excel) format"
      ],
      [
        "format-pdf",
        "PDF inventory"
      ],
      [
        "format-bundle",
        "The full bundle"
      ],
      [
        "share-links",
        "Share links"
      ],
      [
        "export-history",
        "Export history & re-exporting"
      ]
    ]
  },
  {
    "section": "Claims & policies",
    "items": [
      [
        "claim-statuses",
        "Claim statuses"
      ],
      [
        "pp-limit",
        "Personal property limit"
      ],
      [
        "depreciation-schedules",
        "Depreciation schedules"
      ],
      [
        "carrier-profiles",
        "Carrier profiles"
      ],
      [
        "audit-log",
        "The audit log"
      ],
      [
        "photos-tab",
        "The Photos tab"
      ],
      [
        "archive-delete",
        "Archiving & deleting claims"
      ],
      [
        "holdback-recovery",
        "Recovering your holdback"
      ]
    ]
  },
  {
    "section": "In the field",
    "items": [
      [
        "mobile-capture",
        "Capturing from your phone"
      ],
      [
        "mobile-pairing",
        "Pairing a phone to a claim"
      ],
      [
        "mobile-notes",
        "Notes while you shoot"
      ],
      [
        "mobile-review",
        "Reviewing on mobile"
      ]
    ]
  },
  {
    "section": "Estate sale mode",
    "items": [
      [
        "estate-mode",
        "Estate sale mode"
      ],
      [
        "fair-market-value",
        "Fair market value"
      ],
      [
        "condition-status",
        "Condition & status"
      ]
    ]
  },
  {
    "section": "Account",
    "items": [
      [
        "storage-fair-use",
        "Storage & fair use"
      ],
      [
        "billing-plans",
        "Billing & plans"
      ],
      [
        "security-passkeys",
        "Security & passkeys"
      ],
      [
        "team-roles",
        "Team & roles"
      ],
      [
        "api-webhooks",
        "API & webhooks"
      ]
    ]
  },
  {
    "section": "Troubleshooting",
    "items": [
      [
        "trouble-upload",
        "Photos won’t upload"
      ],
      [
        "trouble-wrong-item",
        "An item came back wrong"
      ],
      [
        "trouble-export",
        "An export failed"
      ],
      [
        "notifications",
        "Notifications & alerts"
      ],
      [
        "glossary",
        "Glossary"
      ]
    ]
  }
]

export const DOC_ARTICLES: Record<string, DocArticle> = {
  "quick-start": {
    "title": "Quick start",
    "summary": "The whole loop in five minutes: claim in, photos in, inventory out.",
    "blocks": [
      [
        "p",
        "Kevin turns a folder of photographs into a defensible personal-property inventory. You start a claim, drop the photos, let Kevin identify and price each item, review the worksheet, and export a file. Nothing is submitted anywhere on your behalf — you send what you export."
      ],
      [
        "h2",
        "The five steps"
      ],
      [
        "ol",
        [
          "Start a claim. Claim and policy numbers, date and cause of loss, the insured, the loss address, and the contents coverage limit.",
          "Drop the photos. A folder, a phone dump, or a whole .zip — no total-size cap, up to 15 MB per photo. Duplicates are removed as they arrive.",
          "Review the photo sets. Kevin groups shots taken seconds apart into one set. Merge, split, or exclude before anything is identified.",
          "Let Kevin work. Identification, make and model, content class, three live price comps per item, depreciation from the claim schedule.",
          "Review and export. Every cell is editable. Export the Xactimate spreadsheet, a client PDF, or the full bundle."
        ]
      ],
      [
        "h2",
        "How long it takes"
      ],
      [
        "table",
        [
          [
            "Step",
            "A 44-item claim"
          ],
          [
            "Intake",
            "About a minute"
          ],
          [
            "Upload + staging",
            "A minute or two for 50 photos"
          ],
          [
            "Processing",
            "Around eight minutes, unattended"
          ],
          [
            "Your review",
            "Twenty to forty minutes"
          ],
          [
            "Export",
            "Under a minute"
          ]
        ]
      ],
      [
        "note",
        "Every account starts with 250 free line items — full product, real claims, no time limit. Card verified at signup, not charged until you start Pro."
      ]
    ]
  },
  "first-claim": {
    "title": "Creating your first claim",
    "summary": "What every intake field does, and why the ZIP matters more than it looks.",
    "blocks": [
      [
        "p",
        "From My claims, click New claim. Intake is a single form and every field stays editable later, so do not stall on anything you can look up afterwards."
      ],
      [
        "h2",
        "Claim details"
      ],
      [
        "ul",
        [
          "Claim number and policy number — both print on the export, so they are worth getting right.",
          "Date of loss and cause of loss — cause drives nothing automatically; it is documentation.",
          "Carrier — pick from the list, or add your own. Kevin has no relationship with any carrier and no special behavior per carrier.",
          "Insured name — the person whose property this is. This is not you; your name travels separately as the preparer."
        ]
      ],
      [
        "h2",
        "The loss address"
      ],
      [
        "p",
        "Enter the street, city, state, and ZIP of the loss. The ZIP resolves the sales-tax rate applied to every line item, which is why the address and the tax rate must always agree. If the ZIP does not resolve, Kevin falls back to the default rate in your settings and tells you."
      ],
      [
        "h2",
        "Contents coverage"
      ],
      [
        "p",
        "Policies name contents coverage differently — Coverage C, Personal Property, Contents, Coverage B on a renters policy, Business Personal Property on a commercial one. Pick the label off the declarations page and enter the limit. Kevin then shows a meter as the inventory approaches that number, turning amber at 80% and red over the limit."
      ],
      [
        "note",
        "Enter any prior contents payment in \"already claimed\" so the meter reflects what is actually left."
      ],
      [
        "h2",
        "Processing settings"
      ],
      [
        "ul",
        [
          "Depreciation schedule — straight-line by default. You can add your own schedule here.",
          "Default condition — the starting condition grade for every item, which you override per row."
        ]
      ]
    ]
  },
  "uploading-photos": {
    "title": "Uploading photos",
    "summary": "Formats, size limits, dedupe, and how to shoot so Kevin reads well.",
    "blocks": [
      [
        "p",
        "Drag any combination of JPG, PNG, or HEIC files, a folder, or a whole .zip — no total-size cap, up to 15 MB per photo. iPhone HEIC files are converted on arrival — you do not need to change your camera settings."
      ],
      [
        "h2",
        "Duplicates"
      ],
      [
        "p",
        "Every file is hashed as it uploads. Byte-identical files — the same shot uploaded twice, a burst frame copied into the folder — are discarded, keeping one. This matters because an uncaught duplicate becomes a duplicate line item, which is exactly what a carrier flags."
      ],
      [
        "note",
        "Hashing only catches identical files. Two separate photos of the same television are different files, so they are handled by photo-set grouping in the next step."
      ],
      [
        "h2",
        "How to shoot"
      ],
      [
        "ul",
        [
          "One item per photo. Kevin reads a single item per photograph, so a wide shot of a full room produces one item, not twelve.",
          "Take the model plate. A second photo of the sticker or barcode gets you an exact model number, which produces a much tighter price.",
          "Shoot from a step back, then close. Kevin groups the pair automatically.",
          "Context shots are fine. Mark them skipped in staging and they cost you nothing."
        ]
      ],
      [
        "h2",
        "From the field"
      ],
      [
        "p",
        "The mobile capture screen sends photos straight from your phone to the claim, with an optional note attached to the set you are shooting. Nothing needs to sync through your desktop."
      ]
    ]
  },
  "photo-sets": {
    "title": "Reviewing photo sets",
    "summary": "Kevin proposes the grouping; you approve it before anything is identified.",
    "blocks": [
      [
        "p",
        "Between upload and processing, Kevin proposes photo sets: shots taken within seconds of each other, in the same place, are almost always the same object. Three angles of a sofa become one line item rather than three. A lone photo is simply a set of one."
      ],
      [
        "note",
        "This screen runs before identification. It shows filenames, timestamps, and how far apart the shots were — not item names, because nothing has been identified yet."
      ],
      [
        "h2",
        "What you can change"
      ],
      [
        "ul",
        [
          "Merge — select two or more sets that belong to the same object and combine them.",
          "Split — break a set apart when Kevin grouped two different objects shot back to back.",
          "Skip — mark context shots, blurry frames, or anything you do not want counted."
        ]
      ],
      [
        "h2",
        "The tally"
      ],
      [
        "p",
        "The counter shows photo sets, not line items — 50 photos might propose 47 sets. The item count is not known until identification runs, and it will be lower still once unmatched and context photos fall out."
      ],
      [
        "h2",
        "Notes that steer identification"
      ],
      [
        "p",
        "You can attach a note of up to 120 characters to any set. It rides on the whole set and steers what Kevin looks for: \"the TV is the Sony, not the Samsung,\" or \"this is the mahogany one, not the veneer.\" Notes influence identification only — they never affect price."
      ],
      [
        "note",
        "Notes are pre-processing only. If an item comes back misidentified, correct it by editing the worksheet row, not by re-running identification."
      ]
    ]
  },
  "reviewing-worksheet": {
    "title": "Reviewing the worksheet",
    "summary": "What arrives filled in, what needs you, and the order to work in.",
    "blocks": [
      [
        "p",
        "Processing drops you into a single editable grid — one row per item, every cell yours to change. There is no wizard and no locked step. What Kevin found is all in front of you at once."
      ],
      [
        "h2",
        "What arrives filled in"
      ],
      [
        "ul",
        [
          "Description, make, and model number where they were legible.",
          "Content class, which drives the depreciation math.",
          "Unit cost, from the median of three live retail comps, with a dated link to the comp behind it.",
          "Age and depreciation percent, from the schedule on the claim."
        ]
      ],
      [
        "h2",
        "What needs you"
      ],
      [
        "ul",
        [
          "Room or area — Kevin does not know which room a photo was taken in. This is free text and filterable.",
          "Quantity, where one photo represents several identical items.",
          "Anything left blank. When Kevin cannot find a confident comp it leaves the price empty rather than guessing.",
          "Anything it got wrong. Fix the description and re-price against fresh comps."
        ]
      ],
      [
        "h2",
        "A working order that saves time"
      ],
      [
        "ol",
        [
          "Filter by room and fill the room column in blocks — it is faster than jumping around.",
          "Sort or filter to the unpriced rows and clear those first; they are the ones that hold up an export.",
          "Pin the item panel and tab down the grid, checking each photo against its description.",
          "Check the special-limits flags last, against the policy."
        ]
      ]
    ]
  },
  "exporting-xactimate": {
    "title": "Exporting to Xactimate",
    "summary": "The spreadsheet route into XactContents, start to finish.",
    "blocks": [
      [
        "p",
        "Xactimate does not accept an XML upload for contents. XactContents imports a pre-formatted Excel spreadsheet, and that is exactly what Kevin produces — matching column order, so it imports without cleanup."
      ],
      [
        "h2",
        "Steps"
      ],
      [
        "ol",
        [
          "In the worksheet, click Export claim.",
          "Choose Xactimate (Excel) and download the .xlsx.",
          "In Xactimate desktop, open your estimate and go to the XactContents tab.",
          "Click Import from Excel, choose the file, and import. Make sure the file is closed first."
        ]
      ],
      [
        "note",
        "Kevin never pushes into Xactimate or a carrier system. You download the file and import it yourself, which means nothing moves without your say."
      ],
      [
        "h2",
        "Columns in the file"
      ],
      [
        "p",
        "Number, room or area, quantity, description, make and model, unit cost, extended cost, sales tax, RCV plus tax, age, percent depreciation, dollar depreciation, and ACV. Age prints as a bare number so it lands numeric in Excel, and tax is per line item rather than only as a claim total."
      ],
      [
        "h2",
        "If something looks off after import"
      ],
      [
        "ul",
        [
          "Blank prices mean the item was unpriced in Kevin. Fill those in before exporting.",
          "Numbers stored as text usually means the file was open in Excel when you imported it."
        ]
      ]
    ]
  },
  "editing-cells": {
    "title": "Editing cells",
    "summary": "Which cells you type in, which are calculated, and how the money chain foots.",
    "blocks": [
      [
        "p",
        "Click any editable cell and type. There is no edit mode to enter and no save button — changes commit when you leave the cell, and every one is recorded in the audit log."
      ],
      [
        "h2",
        "Editable versus calculated"
      ],
      [
        "table",
        [
          [
            "Editable",
            "Calculated"
          ],
          [
            "Room / area",
            "Extended cost"
          ],
          [
            "Quantity",
            "RCV + tax"
          ],
          [
            "Description, make, model",
            "Dollar depreciation"
          ],
          [
            "Content class",
            "ACV"
          ],
          [
            "Unit cost",
            ""
          ],
          [
            "Age, percent depreciation",
            ""
          ]
        ]
      ],
      [
        "h2",
        "How the money foots"
      ],
      [
        "code",
        "Extended cost  = Unit cost x Quantity\nRCV + Tax      = Extended cost + (Extended cost x tax rate)\n$ Depreciation = Extended cost x % Depreciation\nACV            = Extended cost + Tax - $ Depreciation"
      ],
      [
        "p",
        "Tax sits inside ACV, and the columns foot left to right. Change a unit cost and everything to its right follows."
      ],
      [
        "h2",
        "Keyboard"
      ],
      [
        "ul",
        [
          "Tab and arrows move between cells.",
          "Enter on the last row appends a new blank row, so you can add items without touching the mouse.",
          "Money cells clear when you focus them — type the new figure straight in. Leave without typing and the old value returns."
        ]
      ],
      [
        "h2",
        "Column widths"
      ],
      [
        "p",
        "Drag a header boundary to resize a column, like a spreadsheet. Double-click a boundary to reset it."
      ]
    ]
  },
  "bulk-actions": {
    "title": "Bulk actions",
    "summary": "Change or remove many rows at once with the checkbox column.",
    "blocks": [
      [
        "p",
        "Tick the checkbox on any row and an action bar appears showing how many rows are selected. Ticking is selection only — it does not open anything or change the item panel."
      ],
      [
        "h2",
        "Re-categorize"
      ],
      [
        "p",
        "Sets the content class on every selected row. Because class drives depreciation, each affected row then waits briefly for the server to return a new percentage, and the cell flashes when it lands. Unpriced rows are skipped — they carry no depreciation to recalculate."
      ],
      [
        "h2",
        "Delete"
      ],
      [
        "p",
        "Removes the selected rows from the inventory after a confirmation. The source photos stay on the claim, so nothing is lost and you can add the item back by hand."
      ],
      [
        "h2",
        "Add item"
      ],
      [
        "p",
        "Appends a blank row at the end and puts the cursor in it. Pressing Enter on the last row does the same thing. A row you add by hand was never seen by identification and never priced, so it is tagged Manual and you enter the value yourself."
      ],
      [
        "note",
        "There is no bulk re-run of identification. If items came back wrong, edit the descriptions and re-price — a second identification pass would not know anything new."
      ]
    ]
  },
  "search-filter": {
    "title": "Search & filter",
    "summary": "Narrowing 142 rows to the handful you are working on.",
    "blocks": [
      [
        "p",
        "Search matches description, make, model, content class, and room at once. Type \"sony\" to see every Sony item; type \"kitchen\" to see everything you have assigned to the kitchen."
      ],
      [
        "h2",
        "The filter popover"
      ],
      [
        "ul",
        [
          "Room — free text, so it matches whatever names you typed.",
          "Barcode matched — items where a barcode or model sticker was read, which are your most reliable rows.",
          "Special limits — classes the policy may cap.",
          "Low confidence — where identification was least certain.",
          "High value — items over a threshold, useful for a final pass."
        ]
      ],
      [
        "h2",
        "Group by class"
      ],
      [
        "p",
        "Toggling group by class sections the grid by content class with a subtotal on each group. This is the fastest way to sanity-check a claim: if Electronics totals more than the whole rest of the house, something is wrong."
      ],
      [
        "h2",
        "What filters do not do"
      ],
      [
        "p",
        "Filtering changes what you see, never what exports. The export always contains the full inventory unless you deleted rows."
      ]
    ]
  },
  "content-classes": {
    "title": "Content classes",
    "summary": "What the class column is for and why it changes the numbers.",
    "blocks": [
      [
        "p",
        "Every item carries a content class — Electronics, Furniture, Clothing, Jewelry, and so on. The class is not decoration: it selects the useful life used to depreciate the item, and it maps to the category code in the exported spreadsheet."
      ],
      [
        "h2",
        "Changing a class"
      ],
      [
        "p",
        "Click the class cell and a searchable list opens showing all classes with the current one ticked. Type to narrow it, or scroll the full list if you are not sure what exists. Picking a new class sends the row for recalculation, and the depreciation cell shows a spinner until the answer comes back."
      ],
      [
        "note",
        "The depreciation percentage is calculated on the server, never in your browser. That is deliberate: it guarantees the figure in your worksheet is the figure in the exported file, to the penny."
      ],
      [
        "h2",
        "Useful life"
      ],
      [
        "p",
        "Each class carries a standard useful life — five years for electronics, fifteen for furniture, three for children’s clothing. Straight-line depreciation divides the item’s age by that life. Useful life is internal to the math and never printed as a column on an export."
      ],
      [
        "h2",
        "Classes Kevin will not auto-price"
      ],
      [
        "p",
        "Jewelry, fine arts, firearms, and furs come back unpriced regardless of what a search might turn up. These need an appraisal or your own judgment, and a machine-picked comparable would not hold up."
      ]
    ]
  },
  "depreciation-overrides": {
    "title": "Depreciation overrides",
    "summary": "Three methods, one cap, and what happens when you type over the number.",
    "blocks": [
      [
        "p",
        "Depreciation arrives already calculated from the schedule attached to the claim. You can override any percentage by typing over it."
      ],
      [
        "h2",
        "The three methods"
      ],
      [
        "table",
        [
          [
            "Method",
            "How it works"
          ],
          [
            "Straight-line (default)",
            "Age divided by the useful life for the class, capped so a salvage floor remains."
          ],
          [
            "Bracketed",
            "A percentage looked up by class and age band — under 1 year, 1 to 2, 3 to 5, 6 to 10, 11 to 15, over 15."
          ],
          [
            "Custom",
            "Percentages you enter yourself."
          ]
        ]
      ],
      [
        "h2",
        "The cap"
      ],
      [
        "p",
        "Straight-line is capped at 90%, so a twenty-year-old five-year-life item does not depreciate to nothing. Something old and still present has salvage value, and a carrier will expect to see it."
      ],
      [
        "h2",
        "Overriding"
      ],
      [
        "p",
        "Type a percentage into the cell and it stops following the schedule — the row is marked as manually set, and the change is recorded with your name and the time. Click the information icon in the cell to see how the figure was reached: the method, the useful life, the age, and whether the cap applied."
      ],
      [
        "note",
        "Unpriced items stay at zero percent. There is no price to depreciate, so a percentage would be meaningless."
      ],
      [
        "h2",
        "Adding your own schedule"
      ],
      [
        "p",
        "On intake, choose Add new schedule to define one: a name, the method, useful life by class, and a maximum. It is then selectable on any future claim."
      ]
    ]
  },
  "rcv-comps": {
    "title": "RCV comps & proof links",
    "summary": "Where the price came from, how to switch it, and what prints on the export.",
    "blocks": [
      [
        "p",
        "Every comp Kevin finds comes from one place: Google Shopping and the Google Immersive Product API, which already spans major retailers, specialty stores, brand-direct storefronts, and marketplaces. There is no list of individual stores to maintain or switch on."
      ],
      [
        "h2",
        "How the price is chosen"
      ],
      [
        "p",
        "Kevin keeps the top three merchant offers for an item and takes the median as the replacement cost. The median is deliberately dull: it resists a single mispriced listing in either direction. When offers disagree by more than 15%, the manufacturer’s own price is weighted to settle it."
      ],
      [
        "h2",
        "Switching comps"
      ],
      [
        "p",
        "Click a unit cost cell and all three comps open — merchant, title, price, and a link to the listing. Pick a different one and the price changes, and so does the proof link on that row. The link always points at the comp actually behind the price."
      ],
      [
        "h2",
        "The proof link"
      ],
      [
        "p",
        "The last column carries a link labelled Link, which opens the listing the price came from. It prints into both the spreadsheet and the PDF, which is what makes a figure defensible months later. If you type a price by hand, the link is blank — an invented price has no source to cite, and you can attach your own with the plus control."
      ],
      [
        "note",
        "Kevin stores the URL and the date it was fetched, not a snapshot of the page. A dead link a year on still shows what was checked and when."
      ],
      [
        "h2",
        "Like kind and quality"
      ],
      [
        "p",
        "When the exact model is discontinued, Kevin prices the nearest equivalent still sold new and records the substitution on the row, visible in the item panel. Replacement cost always holds a new-replacement price — never a used listing, which has already lost value once and would be depreciated a second time."
      ]
    ]
  },
  "unpriced-items": {
    "title": "Unpriced items",
    "summary": "Why some cells arrive blank, and what to do with them.",
    "blocks": [
      [
        "p",
        "When Kevin cannot find a confident replacement price, the cell arrives empty rather than filled with a guess. A wrong number that looks authoritative is worse than an obvious gap, because nobody checks it."
      ],
      [
        "h2",
        "Why an item comes back blank"
      ],
      [
        "ul",
        [
          "The class requires judgment — jewelry, fine arts, firearms, furs.",
          "Too few comparable listings to trust a median.",
          "Nothing matched at all: a handmade piece, something very old, or a photo that was not readable."
        ]
      ],
      [
        "h2",
        "What a blank row looks like"
      ],
      [
        "p",
        "The unit cost cell is simply empty and editable. Everything derived from it shows a dash and contributes nothing to the claim totals. There is no badge, no warning, and no approval step — you type the price in like any other cell."
      ],
      [
        "note",
        "Dollar amount has nothing to do with it. A ten-thousand-dollar sofa prices normally if the comps are there. Kevin only declines when it genuinely does not know."
      ],
      [
        "h2",
        "Filling it in"
      ],
      [
        "ul",
        [
          "Type a figure. The row is tagged Manual and you can attach a proof URL with the plus control.",
          "Or open the item panel, sharpen the description, and re-price — a better description often finds comps where a vague one did not."
        ]
      ],
      [
        "h2",
        "Exporting with blanks"
      ],
      [
        "p",
        "Kevin will not block an export over unpriced rows. The export screen tells you how many there are and you decide whether to proceed. Blank prices export as zero so spreadsheet formulas do not break."
      ]
    ]
  },
  "special-limits": {
    "title": "Special-limits flags",
    "summary": "An amber row means check the policy, not that something is wrong.",
    "blocks": [
      [
        "p",
        "Most policies cap certain categories regardless of what the items are worth — jewelry, firearms, fine arts, and furs are the usual four, often at a couple of thousand dollars per item or in total. Kevin flags rows in those classes in amber so you check the cap before the inventory goes out."
      ],
      [
        "h2",
        "What the flag does"
      ],
      [
        "ul",
        [
          "Tints the row and badges the class cell.",
          "Appears in the filter, so you can see all flagged rows together.",
          "Shows in the export summary as a count."
        ]
      ],
      [
        "h2",
        "What it does not do"
      ],
      [
        "p",
        "It does not block anything, change any number, or stop an export. It is a reminder to look at the declarations page — the actual cap varies by policy and Kevin does not presume to know it."
      ],
      [
        "note",
        "A special-limits flag is not the same as an unpriced item, though they often coincide. The flag is about coverage; unpriced is about whether Kevin could find a price."
      ]
    ]
  },
  "item-panel": {
    "title": "The item panel",
    "summary": "The photo, the comps, and the math for one row — docked beside the grid.",
    "blocks": [
      [
        "p",
        "Click a row number to open the item panel. It shows the source photograph, the editable fields, the comps behind the price with their links, any like-kind substitution note, and the computed totals for that row."
      ],
      [
        "h2",
        "Docking it"
      ],
      [
        "p",
        "The pin in the panel header docks it to a rail on the right of the grid, where it stays open. Once docked it follows you: click or tab into any row and the panel swaps to that item. For a long claim this is the fastest way to check every photograph against its description. Unpin to return it to a centered dialog."
      ],
      [
        "note",
        "The Item panel button in the toolbar opens the docked panel directly, without going through a row first."
      ],
      [
        "h2",
        "Edit and re-price"
      ],
      [
        "p",
        "The most useful control in the panel. Kevin might have read a photograph as \"brown leather sofa\" when you know from the insured that it is an Ethan Allen Conor. Sharpen the description, click re-price, and Kevin searches again against the better description and returns a fresh price with fresh comps. The row is then marked as manually refined, so anyone reading the file later can see a person steered that search."
      ],
      [
        "h2",
        "Moving between items"
      ],
      [
        "p",
        "The arrows in the header step to the previous or next row without closing the panel."
      ]
    ]
  },
  "format-xlsx": {
    "title": "Xactimate (Excel) format",
    "summary": "Column parity with the XactContents template, and what each column holds.",
    "blocks": [
      [
        "p",
        "The .xlsx export matches the XactContents import template column for column, in order, so it imports without cleanup. This is the format most claims leave Kevin in."
      ],
      [
        "h2",
        "The columns"
      ],
      [
        "table",
        [
          [
            "Column",
            "Contents"
          ],
          [
            "#",
            "Line number"
          ],
          [
            "Room / area",
            "What you typed in the room column"
          ],
          [
            "Qty",
            "Quantity"
          ],
          [
            "Description",
            "The item description"
          ],
          [
            "Make · Model",
            "Manufacturer and model number where known"
          ],
          [
            "Unit cost",
            "Replacement cost for one"
          ],
          [
            "Ext. cost",
            "Unit cost times quantity"
          ],
          [
            "Sales tax",
            "Per line, from the claim tax rate"
          ],
          [
            "RCV + tax",
            "Extended cost plus tax"
          ],
          [
            "Age",
            "Years, as a bare number so Excel treats it as numeric"
          ],
          [
            "% Depr.",
            "Depreciation percentage"
          ],
          [
            "$ Depr.",
            "Dollar depreciation"
          ],
          [
            "ACV",
            "Actual cash value"
          ]
        ]
      ],
      [
        "note",
        "Content class and useful life are internal to the depreciation math and are not printed as columns. They would only invite argument."
      ],
      [
        "h2",
        "Values you should expect"
      ],
      [
        "ul",
        [
          "Unpriced items export as 0.00 rather than blank, so formulas in the sheet do not break.",
          "A zero price produces zero depreciation, never negative zero.",
          "Tax appears on every line, not only as a claim total."
        ]
      ]
    ]
  },
  "format-pdf": {
    "title": "PDF inventory",
    "summary": "The client-facing document, and the one place the disclaimer lives.",
    "blocks": [
      [
        "p",
        "The PDF is the readable version of the same inventory — the file you hand an insured, an attorney, or an estate-sale client. It carries a header with the claim details, the full line-item table, and totals."
      ],
      [
        "h2",
        "What the header shows"
      ],
      [
        "ul",
        [
          "Claim and policy numbers, insured, loss address, date of loss.",
          "Who prepared it and when.",
          "The depreciation method used, named explicitly.",
          "The tax rate applied."
        ]
      ],
      [
        "h2",
        "Depreciation disclosure"
      ],
      [
        "p",
        "The PDF states which method produced its figures and recomputes the table for that method, so the document is internally consistent. Under straight-line it also prints the useful life applied to each line, which is usually the first thing anyone questions."
      ],
      [
        "note",
        "The \"not an appraisal\" language lives in the Terms of Service, not stamped on every inventory. Most exports go straight into Xactimate, where a disclaimer would only be noise."
      ],
      [
        "h2",
        "Photos in the PDF"
      ],
      [
        "p",
        "Photographs, comps, and adjuster notes can only travel in the PDF or the bundle — a spreadsheet has no place to put them. If you need the pictures alongside the numbers, this is the format."
      ]
    ]
  },
  "format-bundle": {
    "title": "The full bundle",
    "summary": "Everything at once, as a .zip, for the file.",
    "blocks": [
      [
        "p",
        "The bundle is a single .zip containing the spreadsheet, the PDF inventory, every source photograph, and the audit log. It is the archival copy — what you keep, or send when someone asks for the complete record."
      ],
      [
        "h2",
        "What is inside"
      ],
      [
        "ul",
        [
          "The .xlsx inventory, ready for XactContents.",
          "The PDF inventory.",
          "A photos folder, with filenames tied to their line numbers.",
          "The audit log: every edit, who made it, and when."
        ]
      ],
      [
        "h2",
        "Size"
      ],
      [
        "p",
        "Photographs dominate the size. A large photo claim can land in the hundreds of MB, and a single export is capped at 2 GB. If you only need the numbers, take the spreadsheet instead."
      ],
      [
        "note",
        "The audit log is the part that makes a bundle worth keeping. Two years on it shows exactly what changed and who changed it."
      ]
    ]
  },
  "share-links": {
    "title": "Share links",
    "summary": "Sending an inventory without an email attachment.",
    "blocks": [
      [
        "p",
        "Instead of downloading and attaching, you can mint a link. Anyone with the link sees the inventory in a read-only view; no account is needed."
      ],
      [
        "h2",
        "Controls"
      ],
      [
        "ul",
        [
          "Expiry — the link stops working on a date you set.",
          "What is included — the spreadsheet, the PDF, the photographs, or a subset.",
          "Revoke — kill the link immediately at any time."
        ]
      ],
      [
        "h2",
        "Who opened it"
      ],
      [
        "p",
        "The share sheet lists each view: the email address if the viewer identified themselves, the approximate location, the device, and the time. It is useful evidence that a file was actually received."
      ],
      [
        "note",
        "A share link is still you sending a file. Kevin has no connection into a carrier system and no carrier-facing surface, so nothing arrives anywhere on its own."
      ]
    ]
  },
  "export-history": {
    "title": "Export history & re-exporting",
    "summary": "Every export is kept, versioned, and re-downloadable.",
    "blocks": [
      [
        "p",
        "Exports are listed per claim with their format, size, line count, and when they were produced. Nothing is thrown away, so you can always retrieve exactly what you sent rather than reconstructing it."
      ],
      [
        "h2",
        "Versions"
      ],
      [
        "p",
        "Export the same claim again after edits and you get a new version alongside the old one. The earlier file stays exactly as it was — the version you sent is the version you can still open, which is the whole point of keeping it."
      ],
      [
        "h2",
        "When an export fails"
      ],
      [
        "p",
        "A failure is technical: a generation error, a storage read problem, a share link that could not be minted. You get a reference ID and a retry. It is never a judgment about whether your inventory is ready — Kevin does not gate an export on editorial readiness."
      ],
      [
        "note",
        "Quote the reference ID if you contact us. It resolves directly to the failed job."
      ]
    ]
  },
  "claim-statuses": {
    "title": "Claim statuses",
    "summary": "Four states, and only you close a claim.",
    "blocks": [
      [
        "p",
        "Every claim shows a status you can change by clicking the badge on the claims list."
      ],
      [
        "table",
        [
          [
            "Status",
            "Meaning"
          ],
          [
            "Processing",
            "Identification and pricing are running. Set by Kevin, not by you."
          ],
          [
            "In review",
            "You are working the worksheet. Still an open claim."
          ],
          [
            "Open",
            "Active, waiting on something — usually the carrier or the insured."
          ],
          [
            "Closed",
            "Done. The only status that takes it out of your open count."
          ]
        ]
      ],
      [
        "note",
        "In review is an open claim. Nothing leaves your open count until you mark it Closed, because only you know when a claim is actually finished."
      ],
      [
        "h2",
        "What status changes"
      ],
      [
        "p",
        "Status drives the counts at the top of the claims list and nothing else. It does not lock the worksheet, restrict editing, or affect exports — a closed claim is still fully editable and exportable."
      ]
    ]
  },
  "pp-limit": {
    "title": "Personal property limit",
    "summary": "Tracking the inventory against the coverage cap.",
    "blocks": [
      [
        "p",
        "Policies name contents coverage differently, so Kevin stores both a label you pick at intake and the dollar limit. Coverage C on a homeowners policy, Coverage B on a renters policy, Personal Property or Contents elsewhere, Business Personal Property on a commercial risk."
      ],
      [
        "h2",
        "The meter"
      ],
      [
        "p",
        "The worksheet totals bar and the claim overview both show the inventory against the limit. It runs in the accent color, turns amber at 80%, and turns red once the inventory exceeds the limit."
      ],
      [
        "h2",
        "Already claimed"
      ],
      [
        "p",
        "If a prior contents payment has been made on the same loss, enter it at intake. The meter then measures against what remains rather than the full limit, which is the number that actually matters."
      ],
      [
        "note",
        "Kevin never prints a coverage letter as though it were universal. Whatever you chose at intake is what appears on the export."
      ]
    ]
  },
  "depreciation-schedules": {
    "title": "Depreciation schedules",
    "summary": "Choosing one per claim, and building your own.",
    "blocks": [
      [
        "p",
        "A schedule is chosen per claim, not globally — an independent adjuster works for several carriers under different guidelines, and depreciation is a policy matter rather than a company-wide setting."
      ],
      [
        "h2",
        "What ships"
      ],
      [
        "ul",
        [
          "An industry-standard straight-line schedule, used by default on every new claim.",
          "A bracketed alternative, where a percentage is looked up by class and age band."
        ]
      ],
      [
        "h2",
        "Building your own"
      ],
      [
        "p",
        "On intake, choose Add new schedule. Give it a name, pick the method, set useful life per content class, and set the maximum depreciation. It becomes selectable on any future claim, and the name prints on the PDF so the reader knows which one produced the numbers."
      ],
      [
        "note",
        "Whatever you pick, the calculation happens on the server. That is what guarantees the worksheet and the exported file agree exactly."
      ]
    ]
  },
  "carrier-profiles": {
    "title": "Carrier profiles",
    "summary": "What a profile is for — and what it deliberately does not control.",
    "blocks": [
      [
        "p",
        "A carrier profile stores the details that repeat across claims for the same carrier: contact routing, export preferences, and the policy language you tend to see. It saves retyping."
      ],
      [
        "h2",
        "What a profile does not set"
      ],
      [
        "p",
        "It does not set depreciation, and it does not set special-limits caps. Both are properties of the individual policy, not the carrier — two policies from the same insurer routinely differ. Kevin asks for those per claim on purpose."
      ],
      [
        "note",
        "Kevin has no relationship with any carrier and no carrier-specific behavior. A profile is your record-keeping convenience, nothing more."
      ],
      [
        "h2",
        "Managing profiles"
      ],
      [
        "p",
        "Add, edit, or delete profiles in Settings. Deleting one leaves existing claims untouched — they keep the values they were created with."
      ]
    ]
  },
  "archive-delete": {
    "title": "Archiving & deleting claims",
    "summary": "Both are always available. It is your account.",
    "blocks": [
      [
        "p",
        "Every claim can be archived or permanently deleted from the row menu on the claims list. Neither is gated."
      ],
      [
        "h2",
        "Archive"
      ],
      [
        "p",
        "Reversible, and keeps everything — items, photographs, exports, and the audit log. Archived claims are still reachable under the Archived filter and can be restored at any time. This is the right choice for a finished claim you want out of the way."
      ],
      [
        "h2",
        "Delete"
      ],
      [
        "p",
        "Permanent, and requires typing DELETE to confirm. Everything goes, including the photographs."
      ],
      [
        "note",
        "Kevin does not gate either action for compliance reasons. Kevin is a platform for building content lists, not a compliance system — retention obligations belong to you and the carrier."
      ],
      [
        "h2",
        "Nothing is deleted to save space"
      ],
      [
        "p",
        "Kevin never removes your data to reclaim storage. Closed claims move to archived storage after ninety days, which is slower on first load and nothing else. It is your data."
      ]
    ]
  },
  "estate-mode": {
    "title": "Estate sale mode",
    "summary": "The same engine, a different worksheet.",
    "blocks": [
      [
        "p",
        "Estate sale mode is for estate-sale companies and liquidators rather than insurance claims. The photo-to-inventory pipeline is identical; what changes is the worksheet and what gets exported."
      ],
      [
        "h2",
        "What is different"
      ],
      [
        "table",
        [
          [
            "Insurance worksheet",
            "Estate worksheet"
          ],
          [
            "RCV, depreciation, ACV",
            "Fair market value and sale price"
          ],
          [
            "Content class",
            "Condition grade"
          ],
          [
            "Special-limits flags",
            "Status: for sale, sold, keep, donate"
          ],
          [
            "Xactimate spreadsheet",
            "PDF inventory, .xlsx, or CSV"
          ]
        ]
      ],
      [
        "h2",
        "What it is for"
      ],
      [
        "p",
        "Two documents, really: the inventory you show a prospective client when pitching for the sale, and the final record of what actually sold and for how much."
      ],
      [
        "note",
        "This is not about estates of the deceased or dividing property among heirs. It is a working tool for people who run sales."
      ]
    ]
  },
  "fair-market-value": {
    "title": "Fair market value",
    "summary": "Secondary-market pricing, not replacement cost.",
    "blocks": [
      [
        "p",
        "Estate mode prices to fair market value — what the item would actually fetch resold — rather than what it would cost to replace new. Those are very different numbers, and using the wrong one misleads a client badly."
      ],
      [
        "h2",
        "Where the figure comes from"
      ],
      [
        "p",
        "Comps are drawn from completed secondary-market sales rather than retail listings: sold prices, auction results, and resale platforms. The median of the comps becomes the fair market value, and each figure keeps a dated link to the sale behind it."
      ],
      [
        "h2",
        "Adjusting it"
      ],
      [
        "p",
        "The value cell is fully editable — you will often know a local market better than any comp set does. You can also re-price from the item panel after sharpening the description, and the comps will come back from the same secondary market."
      ],
      [
        "note",
        "Condition is yours to set and does not change the value arithmetically. It is a judgment recorded for the client, and you price accordingly."
      ],
      [
        "h2",
        "Sale price"
      ],
      [
        "p",
        "A separate column records what an item actually sold for. The totals bar shows realized proceeds against the fair market estimate with the variance, which is the number a client asks about first."
      ]
    ]
  },
  "condition-status": {
    "title": "Condition & status",
    "summary": "Grading an item and tracking where it ended up.",
    "blocks": [
      [
        "p",
        "Two dropdowns per row, both yours to set."
      ],
      [
        "h2",
        "Condition"
      ],
      [
        "p",
        "A grade from excellent down to poor, set by you. It does not change the fair market value automatically — a condition grade is a judgment about the object, and you reflect it in the price you set."
      ],
      [
        "h2",
        "Status"
      ],
      [
        "ul",
        [
          "Unassigned — not yet decided.",
          "For sale — going into the sale.",
          "Sold — with the sale price recorded alongside.",
          "Keep — the client is retaining it.",
          "Donate — going to donation, often with a value needed for a receipt."
        ]
      ],
      [
        "h2",
        "Totals by status"
      ],
      [
        "p",
        "The totals bar breaks the inventory down by status, all on fair-market basis so the four buckets sum to the total, with realized proceeds shown separately."
      ],
      [
        "note",
        "Both fields can be set on many rows at once with the checkbox column, which is much faster after a sale than editing row by row."
      ]
    ]
  },
  "storage-fair-use": {
    "title": "Storage & fair use",
    "summary": "Unlimited claims, a generous item allowance, nothing ever deleted.",
    "blocks": [
      [
        "p",
        "Claims are unlimited on every plan — run as many as you like, with no per-claim fee. Two things are metered, because they are the two real variable costs: the line items Kevin prices for you, and the photographs it stores. Neither ever gets in the way of work."
      ],
      [
        "h2",
        "Line items"
      ],
      [
        "ul",
        [
          "Pro includes 2,000 line items per billing month.",
          "Additional items are $0.20 each, added to the following invoice.",
          "A 60-photo kitchen fire is roughly 57 items, so 2,000 covers about thirty-five claims that size in a month.",
          "Going over never locks a claim or blocks an export — the work finishes, the overage bills after."
        ]
      ],
      [
        "note",
        "Estate sales are priced separately at $249 per estate rather than against the monthly allowance, because a single estate can run to thousands of items."
      ],
      [
        "h2",
        "Storage"
      ],
      [
        "ul",
        [
          "Pro includes 500 GB of active storage.",
          "Closed claims move to archived storage after ninety days. Still fully accessible, marginally slower on first load.",
          "Going over the pool triggers an email, never a mid-claim lockout.",
          "Beyond that, additional storage is $19 per month per 500 GB."
        ]
      ],
      [
        "note",
        "Nothing is ever deleted to reclaim space. Tiering closed claims to archived storage is how the cost is managed — not deletion, and not a cap on claims."
      ],
      [
        "h2",
        "Where to see it"
      ],
      [
        "p",
        "Billing settings shows both meters — items used against the monthly allowance, and storage used against the pool — the latter derived from the actual photograph count on your account rather than an estimate."
      ]
    ]
  },
  "billing-plans": {
    "title": "Billing & plans",
    "summary": "Two plans, flat monthly, and 250 free items to start.",
    "blocks": [
      [
        "p",
        "Kevin is a flat monthly subscription, the way you already pay for Xactimate. There is no per-claim charge, no per-seat charge, no per-photo charge, and comps are always included."
      ],
      [
        "h2",
        "The plans"
      ],
      [
        "table",
        [
          [
            "Plan",
            "For",
            "Price"
          ],
          [
            "Pro",
            "Content inventory specialists, IAs and public adjusters",
            "$249 / month · unlimited claims · 2,000 line items, then $0.20 an item"
          ],
          [
            "Enterprise",
            "Carriers, TPAs, and multi-adjuster teams",
            "Custom, volume licensing on one invoice"
          ]
        ]
      ],
      [
        "h2",
        "The free tier"
      ],
      [
        "p",
        "Every account starts with 250 free line items — the full product, on real claims, with no time limit. Your card is verified at signup but not charged. Kevin bills you only when you start Pro, either by choosing it in Billing or by continuing past those 250 items; we email you first, and again at 200 items so it is never a surprise."
      ],
      [
        "note",
        "The item count is append-only. Deleting a line does not give the quota back, because the pricing lookups behind it are already paid for by the time the row appears."
      ],
      [
        "h2",
        "Managing it"
      ],
      [
        "ul",
        [
          "Update the card or billing email in Billing settings.",
          "Download any past invoice as a PDF.",
          "Cancel whenever you like — you keep access through the period you have paid for."
        ]
      ],
      [
        "note",
        "Enterprise adds API access, webhooks, team roles, and claim assignment. Everything else is the same product."
      ]
    ]
  },
  "security-passkeys": {
    "title": "Security & passkeys",
    "summary": "How accounts are protected and what you control.",
    "blocks": [
      [
        "p",
        "Data is encrypted with AES-256 at rest and TLS 1.3 in transit. Sign in with an email and password, with Google, or with a passkey."
      ],
      [
        "h2",
        "Passkeys"
      ],
      [
        "p",
        "A passkey replaces the password with a key held by your device or password manager, so there is nothing phishable. Register one in Settings under Security after your first sign-in."
      ],
      [
        "note",
        "Kevin does not use biometrics. Your device may use a fingerprint or face to unlock the key locally, but no biometric data reaches Kevin."
      ],
      [
        "h2",
        "Active sessions"
      ],
      [
        "p",
        "Security settings lists every signed-in session with device, browser, approximate location, and last activity. You can end any one of them, or end all sessions other than the one you are using — useful if you signed in somewhere you should not have."
      ],
      [
        "h2",
        "Recovery codes"
      ],
      [
        "p",
        "Download a set of one-time codes and keep them somewhere other than the machine you sign in from. Regenerating invalidates the old set immediately."
      ]
    ]
  },
  "team-roles": {
    "title": "Team & roles",
    "summary": "Enterprise: who can see and do what.",
    "blocks": [
      [
        "p",
        "Team management is an Enterprise feature. On Pro you are a single account holder, which is how most independent adjusters and estate-sale professionals work."
      ],
      [
        "h2",
        "Roles"
      ],
      [
        "table",
        [
          [
            "Role",
            "Can"
          ],
          [
            "Owner",
            "Everything, including billing and deleting the account"
          ],
          [
            "Admin",
            "Manage people and settings, no billing"
          ],
          [
            "Adjuster",
            "Work claims assigned to them"
          ],
          [
            "Viewer",
            "Read-only, for a supervisor or a desk reviewer"
          ]
        ]
      ],
      [
        "h2",
        "Inviting people"
      ],
      [
        "p",
        "Invite by email address and set the role. Invitations expire if unused, and you can revoke one before it is accepted."
      ],
      [
        "h2",
        "Claim assignment"
      ],
      [
        "p",
        "Claims can be reassigned between people on the account — necessary when someone leaves, goes on leave, or a desk rebalances workload. Reassignment is recorded in the audit log."
      ],
      [
        "note",
        "There is no per-seat charge. Enterprise is volume licensing on one invoice."
      ]
    ]
  },
  "api-webhooks": {
    "title": "API & webhooks",
    "summary": "Enterprise: opening claims and collecting inventories programmatically.",
    "blocks": [
      [
        "p",
        "Programmatic access is for carriers, TPAs, and multi-adjuster desks that open claims from their own system and want the finished inventory back automatically. If you work claim by claim in the app, you do not need any of it."
      ],
      [
        "h2",
        "Keys"
      ],
      [
        "p",
        "Create scoped keys in Settings — read-only for reporting, write access for creating claims. Keys can be rotated or revoked at any time, and rotation is required at least annually."
      ],
      [
        "h2",
        "Webhooks"
      ],
      [
        "p",
        "Subscribe an endpoint to Kevin lifecycle events rather than polling."
      ],
      [
        "ul",
        [
          "claim.created — a claim was opened.",
          "claim.processing.complete — identification and pricing finished.",
          "claim.item.needs_manual — an item could not be priced confidently.",
          "claim.status.changed — the status moved.",
          "export.generated — a spreadsheet, PDF, or bundle was produced.",
          "export.link.viewed — someone opened a share link."
        ]
      ],
      [
        "note",
        "Every event describes Kevin’s own work. There is no submit endpoint, because Kevin never writes into a carrier system."
      ],
      [
        "h2",
        "A typical integration"
      ],
      [
        "ol",
        [
          "Create the claim with a write-scoped key.",
          "Upload photographs to it.",
          "Wait for claim.processing.complete.",
          "Download the .xlsx and hand it to whatever comes next on your side."
        ]
      ]
    ]
  },
  "mobile-capture": {
    "title": "Capturing from your phone",
    "summary": "Shooting straight into a claim, without a trip through your desktop.",
    "blocks": [
      [
        "p",
        "Open Kevin in your phone browser and photos go straight into the claim you have open. There is nothing to import later and nothing to keep track of on a memory card."
      ],
      [
        "h2",
        "How it works"
      ],
      [
        "ol",
        [
          "Sign in on your phone and pick the claim, or scan the pairing code from your desktop.",
          "Tap the shutter and shoot. Each frame uploads as you go.",
          "The counter shows how many photos are on the claim so far."
        ]
      ],
      [
        "h2",
        "Your camera roll"
      ],
      [
        "p",
        "Photos go from the camera into the claim without being saved to your personal camera roll. That is deliberate: an adjuster does not want two hundred photographs of somebody else’s fire-damaged kitchen sitting in their phone gallery."
      ],
      [
        "note",
        "If you would rather use the phone camera app and upload afterwards, that works too — select the photos from your library like any other upload."
      ],
      [
        "h2",
        "Bad signal"
      ],
      [
        "p",
        "Photos are cached locally when the connection drops and upload themselves once you have service again. You can keep shooting the whole time. Nothing is lost if you walk out of a basement mid-claim."
      ],
      [
        "h2",
        "What to shoot"
      ],
      [
        "ul",
        [
          "One item per photo — Kevin reads a single item per frame.",
          "A second shot of the model plate or barcode whenever there is one.",
          "A step-back shot then a close-up. Kevin groups the pair for you."
        ]
      ]
    ]
  },
  "mobile-pairing": {
    "title": "Pairing a phone to a claim",
    "summary": "Getting the right claim on the phone in a few seconds.",
    "blocks": [
      [
        "p",
        "Pairing points your phone at one specific claim, so you cannot accidentally shoot a kitchen fire into last week’s water loss."
      ],
      [
        "h2",
        "Two ways in"
      ],
      [
        "ul",
        [
          "Scan the code. Open the claim on your desktop, show the pairing code, and scan it with your phone camera. The claim opens already selected.",
          "Sign in on the phone. Sign in and pick the claim from your list. Slower, but it works with no desktop nearby."
        ]
      ],
      [
        "h2",
        "What the code does"
      ],
      [
        "p",
        "It confirms the phone is yours and selects the claim. It expires shortly after being shown, and showing a new one invalidates the old one."
      ],
      [
        "note",
        "A paired phone stays on that claim until you switch. Check the claim name in the header before a long shoot — it is the one mistake that costs real time to unpick."
      ],
      [
        "h2",
        "Signing in on a phone"
      ],
      [
        "p",
        "Email and password, Google, or a passkey — the same three options as the desktop. Kevin does not use biometrics; if your phone asks for a fingerprint it is unlocking a passkey locally and nothing reaches Kevin."
      ]
    ]
  },
  "mobile-notes": {
    "title": "Notes while you shoot",
    "summary": "Telling Kevin what it is looking at before it looks.",
    "blocks": [
      [
        "p",
        "While shooting you can attach a short note to the set you are capturing — up to 300 characters of additional identification Kevin reads when it processes the batch."
      ],
      [
        "h2",
        "What a good note looks like"
      ],
      [
        "ul",
        [
          "\"Sony, not the Samsung next to it\"",
          "\"Solid mahogany, not veneer\"",
          "\"Custom built-in, no model number\"",
          "\"Insured says purchased 2019\""
        ]
      ],
      [
        "h2",
        "What a note cannot do"
      ],
      [
        "p",
        "Notes influence identification only. They never set or adjust a price, and they do not carry into the export as a field. If you need a price to be a particular figure, type it into the worksheet."
      ],
      [
        "note",
        "Notes are pre-processing. Once a batch has been identified, a note will not change anything — correct the worksheet row instead."
      ],
      [
        "h2",
        "Where notes end up"
      ],
      [
        "p",
        "The note travels with the whole set, so every photo in that set inherits it. You will see it again on the staging screen before you press process, where you can edit or remove it."
      ]
    ]
  },
  "mobile-review": {
    "title": "Reviewing on mobile",
    "summary": "What you can usefully do on a phone, and what to leave for the desk.",
    "blocks": [
      [
        "p",
        "The mobile review screen shows what Kevin found — one item at a time, with its photo, description, and price. It is built for checking work in a truck, not for doing the full review."
      ],
      [
        "h2",
        "What works well on a phone"
      ],
      [
        "ul",
        [
          "Confirming an identification against the photo while you are still on site.",
          "Fixing an obviously wrong description.",
          "Setting the room on items you just shot, while you remember which room it was.",
          "Spotting anything that came back unpriced."
        ]
      ],
      [
        "h2",
        "What to leave for the desktop"
      ],
      [
        "p",
        "The full worksheet is a wide grid with fifteen columns, comps beside each row, and filters. It is desktop-first on purpose — a phone cannot show enough of it at once to review two hundred items sensibly."
      ],
      [
        "note",
        "Anything you change on the phone is the same claim. There is no separate mobile copy to merge and nothing to sync manually."
      ]
    ]
  },
  "audit-log": {
    "title": "The audit log",
    "summary": "Who changed what, when — the part that makes a file defensible.",
    "blocks": [
      [
        "p",
        "Every claim keeps a timeline of everything that happened to it: creation, upload, processing, every cell edit, every price override, every export. Entries carry the person, the field, the old value, the new value, and a timestamp."
      ],
      [
        "h2",
        "What gets recorded"
      ],
      [
        "ul",
        [
          "Claim created, and any change to the claim details.",
          "Photos uploaded, and photo sets merged, split, or skipped.",
          "Processing started and finished, with the item count.",
          "Every field edit on every row, including which comp was selected for a price.",
          "Depreciation overrides, flagged as manually set rather than schedule-derived.",
          "Rows added or deleted.",
          "Exports produced, share links minted, and share links opened."
        ]
      ],
      [
        "h2",
        "Why it matters"
      ],
      [
        "p",
        "A year after a claim closes, nobody remembers why a figure was changed. The log answers that without anyone having to. When a carrier questions a number, the log shows whether it came from a comp or from a person, and who that person was."
      ],
      [
        "note",
        "The log is a record, not a conversation. There is no commenting, no mentions, and no message thread — those were considered and left out."
      ],
      [
        "h2",
        "Reading it"
      ],
      [
        "p",
        "Open the Audit tab on any claim. Filter by person, by event type, or by date. It is a single timeline rather than a per-row history, so you read a claim chronologically."
      ],
      [
        "h2",
        "Exporting it"
      ],
      [
        "p",
        "The full bundle includes the audit log as a file. That is the main reason to take the bundle rather than just the spreadsheet."
      ]
    ]
  },
  "photos-tab": {
    "title": "The Photos tab",
    "summary": "Every photograph on the claim, and which item each one backs.",
    "blocks": [
      [
        "p",
        "The Photos tab shows every photograph uploaded to the claim, whether or not it produced a line item. It is where you go when a number looks wrong and you want to see the source."
      ],
      [
        "h2",
        "What each photo shows"
      ],
      [
        "ul",
        [
          "The item it backs, if any — at most one, because Kevin reads a single item per frame.",
          "Its status: matched, unmatched, a context shot, or a duplicate removed at upload.",
          "The room, once you have assigned one on the worksheet.",
          "Capture metadata: device, time, and whether the file carried location data."
        ]
      ],
      [
        "h2",
        "Why photos outnumber items"
      ],
      [
        "p",
        "A 162-photo claim typically yields fewer items — some photos are context shots, some are model-plate close-ups of an item already counted, some are unmatched or too blurry to read, and a few are duplicates. Items are always fewer than photos, never more."
      ],
      [
        "h2",
        "Filters"
      ],
      [
        "ul",
        [
          "By status, to find everything unmatched in one pass.",
          "By room, to check a room’s coverage before leaving a site.",
          "By capture device, useful when two people shot the same job."
        ]
      ],
      [
        "note",
        "Deleting a line item does not delete its photograph. The photo stays on the claim, so you can add the item back or price it differently."
      ]
    ]
  },
  "trouble-upload": {
    "title": "Photos won’t upload",
    "summary": "The handful of things that actually cause this.",
    "blocks": [
      [
        "p",
        "Uploads are resumable, so a stalled batch usually finishes itself once whatever interrupted it clears. If it does not, the cause is almost always one of the following."
      ],
      [
        "h2",
        "Check these first"
      ],
      [
        "ul",
        [
          "File size. Any one photo is capped at 15 MB; there is no total-size cap — Kevin uploads big drops in batches automatically.",
          "File type. JPG, PNG, and HEIC. A .mov or a RAW file will be rejected.",
          "A .zip inside a .zip. Only the outer archive is opened.",
          "Signal. On a phone, photos cache locally and upload when service returns — you can keep shooting."
        ]
      ],
      [
        "h2",
        "HEIC files"
      ],
      [
        "p",
        "iPhone HEIC photos are converted on arrival. You do not need to change your camera setting to JPEG, and conversion does not reduce what Kevin can read."
      ],
      [
        "h2",
        "A photo uploaded but produced no item"
      ],
      [
        "p",
        "That is normal and not an error. Context shots, model-plate close-ups of an item already counted, and frames too blurry to read all land in the Photos tab as unmatched. If it should have produced an item, add the row by hand and attach the price."
      ],
      [
        "note",
        "Still stuck? Email kevin@kevin.co with the claim number. It goes to a person, not a queue."
      ]
    ]
  },
  "trouble-wrong-item": {
    "title": "An item came back wrong",
    "summary": "Correcting a misidentification, and getting a better price out of it.",
    "blocks": [
      [
        "p",
        "Kevin will sometimes read a photograph as \"brown leather sofa\" when the insured tells you it is an Ethan Allen Conor. The fix is to sharpen the description and re-price against it — not to run identification again, which would see exactly the same photograph."
      ],
      [
        "h2",
        "The fix"
      ],
      [
        "ol",
        [
          "Open the item panel from the row number.",
          "Click Edit and re-price.",
          "Correct the description, make, model, or class.",
          "Click re-price. Kevin searches again against the better description and returns a fresh price with fresh comps."
        ]
      ],
      [
        "p",
        "The row is then marked as manually refined, so anyone reading the file later can see a person steered that search rather than a machine guessing."
      ],
      [
        "h2",
        "If re-pricing finds nothing better"
      ],
      [
        "p",
        "Type the figure in yourself. The row is tagged Manual and you can attach your own proof URL with the plus control in the link column — an appraisal, a receipt, or a listing you found."
      ],
      [
        "note",
        "Kevin never re-runs identification on your behalf. A second pass over the same pixels does not know anything new, and it would quietly discard your corrections."
      ],
      [
        "h2",
        "A wholly wrong item"
      ],
      [
        "p",
        "If the photograph produced something that is not there at all, delete the row. The photograph stays on the claim."
      ]
    ]
  },
  "trouble-export": {
    "title": "An export failed",
    "summary": "What a failure means, and what it never means.",
    "blocks": [
      [
        "p",
        "An export failure is technical. Something went wrong producing the file: a generation error, a storage read problem, or a share link that could not be minted. Your claim and every line item are untouched."
      ],
      [
        "h2",
        "What to do"
      ],
      [
        "ol",
        [
          "Click retry. Most failures are transient and clear on a second attempt.",
          "If it fails again, try a different format — a spreadsheet when a bundle fails often points at photo storage rather than the inventory.",
          "Quote the reference ID if you email us. It resolves directly to the failed job."
        ]
      ],
      [
        "note",
        "A failure is never a judgment about whether your inventory is finished. Kevin does not block an export over unpriced rows, missing model numbers, or special-limits classes — it tells you what is there and you decide."
      ],
      [
        "h2",
        "The export screen flagged things but let me through"
      ],
      [
        "p",
        "That is intentional. Kevin surfaces what needs attention and keeps the download buttons live. You know your claim and your carrier; the software does not get a veto."
      ]
    ]
  },
  "notifications": {
    "title": "Notifications & alerts",
    "summary": "What Kevin tells you about, and where.",
    "blocks": [
      [
        "p",
        "Kevin notifies you about its own work — processing finishing, exports completing, share links being opened — and nothing else. There are no digests and no engagement email."
      ],
      [
        "h2",
        "What you get"
      ],
      [
        "table",
        [
          [
            "Event",
            "Why it matters"
          ],
          [
            "Processing complete",
            "The worksheet is ready to review"
          ],
          [
            "Export ready",
            "The file finished generating"
          ],
          [
            "Share link opened",
            "Someone received what you sent"
          ],
          [
            "Export failed",
            "With a reference ID and a retry"
          ],
          [
            "Special-limits flagged",
            "Items the policy may cap, worth checking before you export"
          ],
          [
            "Storage nearing the pool",
            "An email first, never a lockout"
          ],
          [
            "Payment problem",
            "Before anything is interrupted"
          ]
        ]
      ],
      [
        "h2",
        "Where they appear"
      ],
      [
        "p",
        "In the bell in the top bar, and by email for anything you would want to know while away from the app. You choose which categories email you in profile settings."
      ],
      [
        "note",
        "Processing on a large claim takes several minutes. Turn on the email for it and go do something else — you do not need to watch the screen."
      ]
    ]
  },
  "glossary": {
    "title": "Glossary",
    "summary": "The terms on every screen, in plain language.",
    "blocks": [
      [
        "p",
        "Kevin is used by insurance adjusters and by estate-sale professionals, and each group arrives fluent in half of this vocabulary. Here is all of it."
      ],
      [
        "h2",
        "Valuation"
      ],
      [
        "table",
        [
          [
            "Term",
            "Means"
          ],
          [
            "RCV",
            "Replacement cost value — what it costs to buy the item new today. Always a new-replacement price in Kevin, never a used listing."
          ],
          [
            "ACV",
            "Actual cash value — replacement cost less depreciation. What the item is worth in its current condition."
          ],
          [
            "Unit cost",
            "Replacement cost for one of the item."
          ],
          [
            "Extended cost",
            "Unit cost times quantity."
          ],
          [
            "FMV",
            "Fair market value — what an item would fetch resold. Used in estate sale mode instead of RCV."
          ],
          [
            "LKQ",
            "Like kind and quality — pricing the nearest equivalent still sold new when the exact model is discontinued."
          ]
        ]
      ],
      [
        "h2",
        "Depreciation"
      ],
      [
        "table",
        [
          [
            "Term",
            "Means"
          ],
          [
            "Depreciation",
            "The value lost to age and wear, as a percentage and a dollar figure."
          ],
          [
            "Straight-line",
            "Age divided by useful life. Kevin’s default method."
          ],
          [
            "Bracketed",
            "A percentage looked up by class and age band rather than calculated."
          ],
          [
            "Useful life",
            "How many years an item of that class is expected to last. Internal to the math, never an export column."
          ],
          [
            "Salvage floor",
            "The cap that stops something old depreciating to nothing."
          ]
        ]
      ],
      [
        "h2",
        "Coverage"
      ],
      [
        "table",
        [
          [
            "Term",
            "Means"
          ],
          [
            "Personal property limit",
            "The cap on contents coverage. Named Coverage C, Coverage B, Contents, or Personal Property depending on the policy."
          ],
          [
            "Special limits",
            "Categories a policy caps regardless of value — usually jewelry, firearms, fine arts, and furs."
          ],
          [
            "Declarations page",
            "The policy summary that names the coverage and states the limit."
          ]
        ]
      ],
      [
        "h2",
        "In Kevin"
      ],
      [
        "table",
        [
          [
            "Term",
            "Means"
          ],
          [
            "Content class",
            "The category an item belongs to. Drives the depreciation math and the export category code."
          ],
          [
            "Photo set",
            "Several photographs of the same object, grouped so they produce one line item."
          ],
          [
            "Comp",
            "A comparable listing Kevin found, with a price and a dated link."
          ],
          [
            "Proof link",
            "The link to the comp a price came from. Prints on the export."
          ],
          [
            "Unpriced",
            "An item Kevin declined to price. The cell is blank and editable."
          ],
          [
            "Manual",
            "A row whose price you typed rather than took from a comp."
          ],
          [
            "XactContents",
            "The contents module of Xactimate. Imports the spreadsheet Kevin produces."
          ]
        ]
      ],
      [
        "h2",
        "Estate sale"
      ],
      [
        "table",
        [
          [
            "Term",
            "Means"
          ],
          [
            "Condition grade",
            "Your assessment of the object, from excellent to poor. Set by you, not calculated."
          ],
          [
            "Status",
            "Where an item ended up: for sale, sold, keep, or donate."
          ],
          [
            "Realized",
            "What items actually sold for, against the fair market estimate."
          ]
        ]
      ]
    ]
  },
  "holdback-recovery": {
    "title": "Recovering your holdback",
    "summary": "Turn replaced items into a recovery request the carrier desk can pay.",
    "blocks": [
      [
        "p",
        "On an RCV policy the carrier pays ACV up front and holds back the depreciation. When the insured actually replaces an item, that holdback becomes recoverable. Kevin tracks it per line and builds the request document for you."
      ],
      [
        "h2",
        "How it works"
      ],
      [
        "ol",
        [
          "Open Recovery — from the claim overview, open the Recovery tab. Every line from the worksheet is there with its holdback amount already computed.",
          "Enter the actual cost — what the insured actually paid. For multi-unit lines, set how many of the units were replaced; Kevin prorates the recoverable amount per unit.",
          "Attach the receipt — one per line. A line with a cost but no receipt still exports; it prints MISSING in amber so the desk sees the gap instead of a silently dropped line.",
          "Export the request — as an .xlsx or a PDF RCV Report, with or without the receipt files. Send it the way you send everything else — download or share link."
        ]
      ],
      [
        "h2",
        "What the recoverable amount is"
      ],
      [
        "p",
        "Per line, recovery is capped at the smaller of the withheld depreciation and what was actually spent. Replace a $1,200 item for $900 and the request claims the holdback up to $900 — the carrier never pays out more than the insured spent. These caps come from the backend; the sheet shows them per line as “Back to insured.”"
      ],
      [
        "h2",
        "Batches are normal"
      ],
      [
        "p",
        "Insureds replace items over months. Export a recovery request whenever there is something new to claim — each export is a fresh snapshot of every line with an actual cost entered. Nothing forces you to wait until everything is replaced."
      ],
      [
        "h2",
        "What the exports contain"
      ],
      [
        "table",
        [
          [
            "Export",
            "Contents"
          ],
          [
            "RCV Report · .xlsx",
            "Static-value spreadsheet of claimed lines — row #, item, holdback, actual cost, claimed amount, receipt filename."
          ],
          [
            "RCV Report · PDF",
            "The same request as a formatted document, with an appendix indexing each receipt by worksheet row number."
          ],
          [
            "Receipts · .zip",
            "Just the receipt files, named by row (receipt_0001.pdf), for a desk that already has the request."
          ],
          [
            "Worksheet + receipts · .zip",
            "The request document plus the receipt files as separate originals beside it — the PDF’s appendix is the index."
          ]
        ]
      ],
      [
        "note",
        "Receipts are never merged into one flattened PDF — originals travel as separate files so their metadata and quality survive."
      ]
    ]
  }
}
